Default: &defaults
  user: trevorsmith
  password: trevorsmith
  host: localhost
  port: 5432
  database: trevorsmith
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: trevorsmith_test
  <<: *defaults

Staging:
  database: trevorsmith_staging
  poolsize: 100
  <<: *defaults

Production:
  user: medcpitgeuzwdg
  password: AqQZ2FD--nvUk277zlNY8NqkRz
  database: d3luagip7vb2nd
  host: ec2-54-243-190-226.compute-1.amazonaws.com
  database: d3luagip7vb2nd
  poolsize: 100
  <<: *defaults
